import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { AccessPerformanceCapacityService } from '../src/domain.mjs';
import { AtomicStore } from '../src/store.mjs';

class MemoryStore { constructor() { this.database = { accessPerformanceCapacityReviews: [] }; this.writes = 0; } read() { return structuredClone(this.database); } write(data) { this.database = structuredClone(data); this.writes += 1; } }
const owner = { id: 'owner-847', role: 'evidence_owner' };
const input = { supplierId: 'SUP-847', evidenceReference: 'EVD-847', capacityReference: 'CAP-847-ACCESS-01', capacityScope: 'access_commitment_capacity' };
const chain = [{ action: 'assessCapacity', role: 'capacity_assessment_analyst' }, { action: 'verifyAvailability', role: 'capacity_availability_verifier' }, { action: 'validateReservation', role: 'capacity_reservation_validator' }, { action: 'authorizeCapacity', role: 'capacity_authority' }, { action: 'releaseCapacity', role: 'capacity_registrar' }];

describe('AccessPerformanceCapacityService', () => {
  it('records the complete independently controlled capacity lifecycle', () => { const store = new MemoryStore(); const service = new AccessPerformanceCapacityService(store); let record = service.submit(input, owner, 'request-submit-847'); for (const step of chain) record = service.transition(record.id, step.action, { note: step.action }, { id: step.role, role: step.role }, `request-${step.action}-847`); expect(record.status).toBe('capacity_released'); expect(record.events.map((event) => event.type)).toContain('capacity_released'); expect(store.writes).toBe(6); });
  it('rejects invalid input and invalid role or order without mutation', () => { const store = new MemoryStore(); const service = new AccessPerformanceCapacityService(store); expect(() => service.submit({ ...input, capacityScope: 'other' }, owner, 'request-invalid-847')).toThrow('capacity scope is invalid'); const record = service.submit(input, owner, 'request-state-847'); expect(() => service.transition(record.id, 'assessCapacity', { note: 'attempt' }, owner, 'request-role-847')).toThrow('role capacity_assessment_analyst is required'); expect(() => service.transition(record.id, 'validateReservation', { note: 'order' }, { id: 'validator', role: 'capacity_reservation_validator' }, 'request-order-847')).toThrow('access-performance capacity review must be availability_verified'); expect(store.writes).toBe(1); });
  it('rejects duplicate requests, missing records, and terminal transitions', () => { const store = new MemoryStore(); const service = new AccessPerformanceCapacityService(store); let record = service.submit(input, owner, 'request-repeat-847'); expect(() => service.transition(record.id, 'assessCapacity', { note: 'repeat' }, { id: 'assessor', role: 'capacity_assessment_analyst' }, 'request-repeat-847')).toThrow('request identifier was already used'); expect(() => service.get('missing-847')).toThrow('access-performance capacity review was not found'); for (const step of chain) record = service.transition(record.id, step.action, { note: step.action }, { id: step.role, role: step.role }, `terminal-${step.action}-847`); expect(() => service.transition(record.id, 'releaseCapacity', { note: 'retry' }, { id: 'registrar', role: 'capacity_registrar' }, 'retry-release-847')).toThrow('access-performance capacity review must be capacity_authorized'); });
  it('recovers an absent capacity data file', () => { const directory = mkdtempSync(join(tmpdir(), 'access-performance-capacity-')); try { const store = new AtomicStore(join(directory, 'data', 'access-performance-capacity-reviews.json')); expect(store.read()).toEqual({ accessPerformanceCapacityReviews: [] }); } finally { rmSync(directory, { recursive: true, force: true }); } });
});
